version: '3'
services:
  app-monitoreo:
    image: sistemamonitoreo:latest
    container_name: sistemamonitoreo
    depends_on:
    - rabbitmq
    ports:
      - 8081:8080
    networks:
      - terraminera-network
  app-gerencia:
    image: sistemagerencia:latest
    container_name: sistemagerencia
    depends_on:
    - rabbitmq
    ports:
      - 8082:8080
    networks:
      - terraminera-network
  app-enviocoordenadas:
    image: enviocoordenadas:latest
    container_name: enviocoordenadas
    depends_on:
    - rabbitmq
    networks:
      - terraminera-network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: terraminera-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - terraminera-network
networks:
  terraminera-network:
    driver: bridge